blueprint:
  name: Synchronize Two Entities' States
  description: "Synchronize the on/off state of 2 entities"
  domain: automation
  input:
    main_entity:
      name: Main Entity
      description: >-
        Main entity we monitor. If this synchronization is one-way, then only
        main entity's state will be synced to secondary entity's state.
      selector:
        entity:
    secondary_entity:
      name: Secondary Entity
      description: >-
        Secondary entity we monitor. 
      selector:
        entity:
    is_one_way_sync:
      name: Is One-way Sync
      description: >-
        This synchronization will be one-way if this is set to 'true'. It means
        the automation will only set secondary entity's state to main entity's
        current state when main entity's state changes.
      default: false
      selector:
        entity:
          domain: input_boolean
    sync_delay:
      name: Sync Delay
      description: >-
        Delay before we set sync entities's states. Put number of seconds or 'HH:MM:SS'.
        If any of main entity or secondary entity's state got changed during the delay period,
        this sync will be canceled.
      default: "0"
      selector:
        entity:
          domain: input_text
    off_delay:
      name: Off Sync Delay
      description: >-
        Delay before we turnning off both entitys of due to state change.
        Put number of seconds or 'HH:MM:SS'.
      default: "0"
      selector:
        entity:
          domain: input_text
mode: queued
max: 5
variables:
  main_entity: !input "main_entity"
  secondary_entity: !input "secondary_entity"
  is_one_way_sync: !input "is_one_way_sync"
  sync_delay: !input "sync_delay"
  off_delay: !input "off_delay"
trigger:
  - platform: state
    entity_id: !input "main_entity"
  - platform: state
    entity_id: !input "secondary_entity"
condition:
  - condition: template
    # Only support on/off.
    value_template: "{{ trigger.to_state.state == 'on' or trigger.to_state.state == 'off' }}"
  - condition: template
    # Entity state's not equal.
    value_template: "{{ states(main_entity) != states(secondary_entity) }}"
  - condition: template
    # If it's secondary entity's state change, then this must not be one-way sync.
    value_template: "{{ not (trigger.from_state.entity_id == secondary_entity and is_one_way_sync | lower == 'true') }}"
action:
  - delay: "{% if trigger.to_state.state == 'off' %} {{ off_delay }} {% else %} {{ sync_delay }} {% endif %}"
  - service_template: "homeassistant.turn_{{ trigger.to_state.state }}"
    data_template:
      entity_id: "{% if trigger.from_state.entity_id == main_entity %} {{ secondary_entity }} {% else %} {{ main_entity }} {% endif %}"
